spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.148:3306/subway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: masterpw

  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: validate
