spring:
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: testpw
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  logging:
    level:
      org.hibernate.SQL: debug
